### ISSUE TITLE
Dim Headings and Subheadings

### ISSUE THREAD

**Issue by brianbancroft** [adventice/census#3]
Hey there, and thanks for building this! 

- I'm not the most familiar with the census, and wasn't able to find a directory for all the dimensions (dim) numbers
- It's probably useful to have one handy as a join table in order to assist developers who are not familiar with the 2016 census. 
- If it's useful to you, I've done a bit of the legwork: 
    - This [gist](https://gist.github.com/brianbancroft/670cfa5618f1739f65c42f91b6b775be) contains a stripped tsv and instructions to integrate with the `geo` db

This repo was a timesaver. Thanks again for making this happen!

**Comment by samueltc** [comment]
Hi Brian,

That would be great if you could make a PR with your [gist](https://gist.github.com/brianbancroft/670cfa5618f1739f65c42f91b6b775be).

**Comment by brianbancroft** [comment]
Sure thing! Python isn't my main language right now, but I'll fork and PR what I've got so that it can be of use. 

I've got a few things I need to wrap up before, so it'll be a handful of days

**Comment by brianbancroft** [comment]
#4
